package cshr.careersite.model;

public enum SideNavMenu {
    DASHBOARD,
    MEDIA,
    MEDIALIBRARY,
    MEDIAADDNEW,
    PAGES,
    PAGESALLPAGES,
    PAGESNEW,
    WORKFLOWS,
    WORKFLOWSINBOX,
    WORKFLOWSHISTORY,
    WORKFLOWSREPORTS,
    USERS,
    USERSALLUSERS,
    USERSADDNEW,
    USERSPROFILE,
    USERSROLES,
    USERSADDNEWROLE,
    USERSTEAMS,
    SNIPPETS
}
